### ISSUE TITLE
Fehlverhalten: Geräte weiterhin verfügbar, auch ohne gestarteten Node-Red-Server

### ISSUE THREAD

**Issue by DrHouseIT-Daniel** [DrHouseIT/everHome2MQTT#2]
# Geräte in HomeAssistant werden weiterhin als verfügbar angezeigt, obwohl Node-RED nicht gestartet ist

## Beschreibung:
Es wurde ein Fehlverhalten festgestellt, bei dem die Geräte in HomeAssistant weiterhin als verfügbar angezeigt werden, selbst wenn der Node-RED-Server nicht gestartet ist.

## Auswirkungen:
- Geräte werden fälschlicherweise als verfügbar dargestellt, obwohl keine Verbindung zum Node-RED-Server besteht.
- Dies kann zu Verwirrung führen, da die Steuerung der Geräte in HomeAssistant nicht mehr möglich ist, obwohl sie als online angezeigt werden.

## Ursache:
Dieser Fehler tritt wahrscheinlich aufgrund einer fehlerhaften Konfiguration des **MQTT Last-Will-Topics** auf. Das Last-Will-Topic sollte die Verfügbarkeit der Geräte korrekt signalisieren, sobald die Verbindung abbricht, was jedoch derzeit nicht geschieht.

## Lösungsansatz:
- Überprüfe und korrigiere die Konfiguration des **MQTT Last-Will-Topics**. Es muss sichergestellt werden, dass die Geräte bei Verbindungsverlust als nicht verfügbar markiert werden.
- Die zusätzliche Konfiguration der "Nachricht nach Verbindungsabbau" könnte ebenfalls Abhilfe schaffen.

![Screenshot zur Konfiguration](https://github.com/user-attachments/assets/41a939cb-010c-4881-8782-ba686cb12ba1)

## Weiteres Problem:
Es wurde ebenfalls festgestellt, dass der **MQTT Status** innerhalb von 1 Sekunde zweimal gesendet wird. Dies könnte auf eine unnötige doppelte Verbindung hinweisen. Das Entfernen der markierten Verbindung sollte Abhilfe schaffen.

![Screenshot zur doppelten Verbindung](https://github.com/user-attachments/assets/6ee74944-5fd3-4160-9c11-767c2706bc9e)

## Weiteres Vorgehen:
- Überprüfe die **MQTT Last-Will-Topic**-Konfiguration und sorge dafür, dass Geräte nach einem Verbindungsabbruch korrekt als offline markiert werden.
- Entferne die unnötige doppelte Verbindung, um den mehrfachen Versand des MQTT-Status zu verhindern.

**Comment by DrHouseIT** [comment]
Fehler in Release #8 behoben
