### ISSUE TITLE
Everhome integriert aber alle Rolläden rot, Entitäten nicht verfügbar

### ISSUE THREAD

**Issue by MOW2469** [DrHouseIT/everHome2MQTT#24]
Hi,
habe gestern entlich die Integration meiner Everhome Cloudbox hinbekommen.
Die Gruppen, wie Wohnzimmer, Schlafzimmer usw. die ich auf der Cloudbox angelegt habe sind komischerweise in HA verfügbar und
lassen sich bedienen.
Aber die einzelnen Rolläden, insgesamt 14 Stück erscheinen zwar, sind aber nicht verfügbar.

Hat jemand so etwas schon mal gehabt ?

Gruß Marc
![HA_Everhome](https://github.com/user-attachments/assets/3dd36336-387f-4675-8420-f7e8e1655d9f)

**Comment by DrHouseIT-Daniel** [comment]
HI, schau mal bitte, ob im Control-Center von everHome2MQTT alles Verbunden ist. Könnte mir vorstellen, dass da Node-Red fehlt.

![image.png](https://github.com/user-attachments/assets/9580da4f-bda2-4461-bdbd-5d9267bec24c)

**Comment by MOW2469** [comment]
Denn Eintrag finde ich bei mir gar nicht.....
![HA_Everhome2](https://github.com/user-attachments/assets/5d6e919a-44ba-408c-8afa-c78e30950b35)

**Comment by DrHouseIT-Daniel** [comment]
Klicke mal auf _28 Geräte_ .
Dort müsstest du es finden.

**Comment by MOW2469** [comment]
Ich Vollpfosten....klar....sieht aber gut aus soweit
![HA_Everhome3](https://github.com/user-attachments/assets/f596233f-e56c-4eb2-910e-597bcef6b84a)

**Comment by MOW2469** [comment]
nein, grad gesehen ....Note Red ist getrennt

**Comment by MOW2469** [comment]
Hast Du eine Lösung für mich ?

**Comment by DrHouseIT-Daniel** [comment]
Prüfe bitte in den Kontextdaten (siehe Video), ob die Ip-Adresse richtig ermittelt wurde.
Das muss die Adresse von deinem HA sein.
![image](https://github.com/user-attachments/assets/fb8374e3-4ae4-4603-b644-457be6db23cc)

Danach schau mal bitte nach, ob alle 10 Sekunden eine Debug-Nachricht erzeugt wird, wenn du den Debug-Node wie im Video gezeigt wird, aktivierst.


https://github.com/user-attachments/assets/e5fc11ee-9ff9-40f0-9689-df44845f3779

**Comment by MOW2469** [comment]
Guten Morgen, hab das grad mal alles durchgespielt. Danke für die gute Anleitung.
Bei dem Debug kommt bei mir gar keine Meldung......
Die IP stimmt mit meinem HA überein

![Everhome_Integration_Screenshot_1](https://github.com/user-attachments/assets/6245338a-81ff-4dd3-8e32-6f5cf48f9ef1)

![Everhome_Integration_Screenshot_2](https://github.com/user-attachments/assets/2af36acd-090a-4859-872c-3032f9123f4d)

**Comment by MOW2469** [comment]
Auch das "Verfügbarbeit entfernen" hat leider nichts gebracht. Gruß

![Everhome_Integration_Screenshot_3](https://github.com/user-attachments/assets/487222a9-d1fd-44a4-8e84-e84d1e8336b7)

**Comment by DrHouseIT-Daniel** [comment]
Hi, hast du den Debug-Node aktiviert (Rechts auf den kreis klicken)?
Benutzt du SSL? Falls ja, dann schalte das mal aus.

**Comment by MOW2469** [comment]
Hi, SSL hab ich aus, deshalb wunderts mich das note_red_url_protocol https steht.
Ich find den Kreis nicht.....

**Comment by DrHouseIT-Daniel** [comment]
Ok.
Dann mach mal folgende Änderung und starte danach die Flows neu.

https://github.com/user-attachments/assets/5881240b-4618-47fa-b134-df3d5089991f


![image](https://github.com/user-attachments/assets/33dfa289-a222-48fe-92de-53572f5c1251)

Dann prüfen, was in note_red_url_protocol angegeben ist.
Dort müsste dann http:// gesetzt sein.

Ggf. Aktualisieren Button drücken.
![image](https://github.com/user-attachments/assets/c0c4d764-c985-4638-81ce-4264cea9c3c3)

**Comment by MOW2469** [comment]
Hab`s geändert auf http, bringt leider nichts. Bekomme aber die Ansicht die Du oben im letzten Bild hast auch nirgends zu sehen. Gerade mal alles noch neu gestartet. Im node steht jetzt http:// aber ist im MQTT immer noch getrennt.......bin kurz davor Dir nen Acount anzulegen das Du selber schauen kannst. Hab bis jetzt über 150 Geräte Problemlos integriert bekommen, aber jetzt komm ich echt nicht weiter....

**Comment by DrHouseIT-Daniel** [comment]
Können wir gerne so machen.
Melde dich privat in discord bei mir.

**Comment by DrHouseIT-Daniel** [comment]
Das Problem konnte gelöst werden.
@MOW2469 hatte einen Benutzernamen für http_node und http_static in der Konfiguration von Node-RED angegeben.
Das wird zur Zeit nicht von everHome2MQTT unterstützt.

Die Einstellung muss wie folgt aussehen:
![image](https://github.com/user-attachments/assets/729bd582-e27f-4cc8-983c-ad0f19b0d3ad)

**Comment by MOW2469** [comment]
Daniel....Du bist der Beste !!!
