### ISSUE TITLE
Weboberläche von everhome2mqtt nicht vorhanden & "Verbindung wird hergestellt"

### ISSUE THREAD

**Issue by taylan40** [DrHouseIT/everHome2MQTT#9]
Hallo,

ich habe mich das erste mal an dieser Integration versucht. First things First: VIELEN DANK für eure MÜHEN!

OIch habe leider das problem, dass ich die "weboberfläche vom everhome2mqtt" nicht sehe und somit auch keine ClientID & Client Secret einreichen kann. entsprechend der Doku habe ich alle Schritte 1:1 nach gemacht... 
Kann es ggfs. daran liegen, dass ich meinen Mosquitto Broker bereits als zigbee2mqtt verwende und es deshalb nicht funktioniert?

**Comment by DrHouseIT-Daniel** [comment]
Hi, hast du Node-Red in Home Assistant als Add-on installiert oder läuft es auf einem Container?

Du solltest als erstes prüfen, ob die Serverdatei vorhanden ist.
`/homeassistant/everHome2MQTT/server/everHome2MQTT.js`

![image](https://github.com/user-attachments/assets/5ba3c9d7-1513-40a3-955b-9c7fb8104a2a)

Falls das nicht der Fall sein sollte, dann führen [diesen Schritt](https://github.com/DrHouseIT/everHome2MQTT/blob/main/README.de.md#everhome2mqtt-server) durch.

Wenn die Datei vorhanden ist, dann schau mal, ob der Prozess des Servers läuft.
Das sieht man daran, dass der Status Blau ist und eine Prozessnummer angezeigt wird.

![2024-10-22_14h44_24](https://github.com/user-attachments/assets/68653748-c83b-4f91-807c-7902960d7cdb)

**Comment by taylan40** [comment]
Hi, ja da die Datei ist dort. 
Welchen Port bzw. welche URL gebe ich hier ein? 
<img width="491" alt="2024-10-22 15_27_04-Node-RED – Home Assistant" src="https://github.com/user-attachments/assets/b2228c9f-8a18-41d7-83f6-5aafeafe02bf">
<img width="444" alt="2024-10-22 15_28_08-Node-RED – Home Assistant" src="https://github.com/user-attachments/assets/f387f31a-6da8-4a8b-9c63-3ea5851a6e76">
Leider habe ich auch nicht ganz funktionierende Flows... siehe bilder...

**Comment by DrHouseIT-Daniel** [comment]
Hi,
schön das die Datei vorhanden ist.
Läuft der Prozess? (siehe meine Frage oben).

**Zum Mqtt:**
Wenn du Z.B Mosquito als Add-on in Home Assistent installiert hast und nichts geändert hast, dann sollte
**Server:** localhost
**Port:** 1883
passen.

Wenn du keinen zusätzlichen Benutzer für MQTT angelegt hast, dann sollte als Benutzername und Passwort deine Log-In Daten für Home Assistant funktonieren.

https://github.com/user-attachments/assets/da3fba4e-a533-4950-8e79-4f6dbeb2c2bf

**Comment by taylan40** [comment]
Hi, lieben Dank, der Port sollte, passen.
Der Json File ist ebenfalls drin. 
Jetzt läuft der Prozess immer noch nicht:
<img width="277" alt="2024-10-22 16_12_23-File editor – Home Assistant" src="https://github.com/user-attachments/assets/eb7623e9-1f38-4995-b588-bfa6caa8a1af">
<img width="649" alt="2024-10-22 16_11_32-Node-RED – Home Assistant" src="https://github.com/user-attachments/assets/575453e6-8bb2-4930-aeb2-fe36d1470690">
<img width="735" alt="2024-10-22 16_11_07-Node-RED – Home Assistant" src="https://github.com/user-attachments/assets/62cb9ed9-14fe-4924-b054-b5b376251e09">

ich stolpere noch an diesem Schritt:
<img width="517" alt="2024-10-22 16_18_04-everHome2MQTT_README de md at main · DrHouseIT_everHome2MQTT" src="https://github.com/user-attachments/assets/ad26f0e6-387b-4717-b4b0-1b19de5f31d8">

**Comment by taylan40** [comment]
Also wirklich Dumm gefragt: Wo ist die Weboberfläche des "everhome2MQTT" Servers?

**Comment by DrHouseIT-Daniel** [comment]
Damit ist aus **3.** die Adresse "http://homeassistant.local:3000/" gemeint.
Du kannst aber den Server nicht erreichen, weil er nichts gestartet wurde (siehe Gelbe Status **rc:1** in deinem Screenshot).
Da gilt es jetzt herauszufinden, was da das Problem ist.

Bitte aktiviere den Debug-Knoten.
Danach musst du die Flows neu starten.
Damit du die Fehlermeldung siehst, musst du in die Debug-Anzeige wechseln.
Entweder über das Käfer-Icon oder über das Burger-Menü.
Bitte Poste die Fehlermeldung
 
![2024-10-22_17h24_10](https://github.com/user-attachments/assets/26b6023b-8f63-4ed5-b686-67e62e09b189)

**Comment by taylan40** [comment]
Hi, hier die Fehlermeldung
<img width="1440" alt="Bildschirmfoto 2024-10-22 um 21 41 33" src="https://github.com/user-attachments/assets/ac6ed09f-b035-4350-952b-f99608e9240c">

**Comment by DrHouseIT-Daniel** [comment]
Sorry, ich habe einen wichtigen Schritt (das Übernehmen der Flows).
Habe https://github.com/DrHouseIT/everHome2MQTT/issues/9#issuecomment-2429597438 upgedatet.
Bitte teste es erneut und berichte, ob nun eine Meldung angezeigt wird.

Die Meldung, die du gepostet hast, kommt nach jedem Start.
Sie sagt aus, dass du kein Passwort vergeben hast, mit dem deine _Credentials_ verschlüsselt werden.
Das System verwendet dann ein zufälliges Passwort. 
Das ist aber jetzt für unser Problem nicht relevant.

**Comment by taylan40** [comment]
Guten Morgen, dieses mal habe ich tatsächlich eine MEldung erhalten: 

object
_msgid: "07ef8f8c1de28eca"
append: "http://192.168.178.156:1880/endpoint/restart 3000"
rc: object
code: 0
payload: string
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at doListen (node:net:2014:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1844:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 3000
}

Node.js v18.20.4
<img width="177" alt="2024-10-23 09_37_22-Node-RED – Home Assistant" src="https://github.com/user-attachments/assets/d1250c10-6513-4b60-8d0c-70f890f62593">

**Comment by taylan40** [comment]
Ergänzung: diese Meldung kam ebenfalls noch: 

23.10.2024, 09:36:47[node: bd497c76fb3c9e75](http://homeassistant.local:8123/api/hassio_ingress/pKrnwdQg3zBN9XT_cxgibxDMmq1dI17Rl42JuySFXHA/#)
msg : Object
object
_msgid: "07ef8f8c1de28eca"
append: "http://192.168.178.156:1880/endpoint/restart 3000"
rc: object
code: 0
payload: object
code: 1

**Comment by DrHouseIT-Daniel** [comment]
OK.
Das bedeutet, dass der Port 3000 bereits verwendet wird.
Das ist nicht schlimm.
Du kannst den Port ändern in der [Config.yaml](https://github.com/DrHouseIT/everHome2MQTT/blob/main/docs/Config.yaml/README.de.md#72-ports)-Datei.
Test mal 3005.
Wichtig: Danach musst du in Node-Red die Flows neu starten.
![image](https://github.com/user-attachments/assets/05ce6f66-b032-4f76-aa84-169f0c17bc84)

**Comment by taylan40** [comment]
Das ist das Resultat: 
<img width="805" alt="2024-10-23 10_03_16-Dashboard – Home Assistant" src="https://github.com/user-attachments/assets/7f69c7a2-be05-4744-8889-4b51d46f8b58">

**Comment by DrHouseIT-Daniel** [comment]
Sehr gut.
Dann sollte es ja jetzt funktionieren.

**Comment by DrHouseIT** [comment]
Logging wurde verbessert und Dokuentation angepasst.
#11
